using LanguagePractice.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace LanguagePractice.Services
{
    /// <summary>
    /// エクスポート結果
    /// </summary>
    public class ExportResult
    {
        public bool Success { get; set; }
        public string? FilePath { get; set; }
        public string? ErrorMessage { get; set; }

        public static ExportResult Succeeded(string filePath) => new() { Success = true, FilePath = filePath };
        public static ExportResult Failed(string message) => new() { Success = false, ErrorMessage = message };
    }

    /// <summary>
    /// PoetryLab 整形テキスト出力サービス
    /// </summary>
    public class PoetryExportService
    {
        private static readonly string ExportFolder =
            Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments), "LanguagePractice", "PoetryLabExports");

        private readonly PoetryDatabaseService _db;

        public PoetryExportService(PoetryDatabaseService db)
        {
            _db = db;
        }

        /// <summary>
        /// Runの成果物を整形テキストとしてエクスポート
        /// </summary>
        public ExportResult Export(int projectId, int runId)
        {
            try
            {
                // 1. データ取得
                var project = _db.GetProject(projectId);
                if (project == null)
                    return ExportResult.Failed("プロジェクトが見つかりません");

                var run = _db.GetRun(runId);
                if (run == null)
                    return ExportResult.Failed("Runが見つかりません");

                if (run.Status != "SUCCESS")
                    return ExportResult.Failed("Runが完了していません");

                var assets = _db.GetTextAssetsByRun(runId);
                var issues = _db.GetIssuesByRun(runId, new[] { "S", "A" });
                var compare = _db.GetCompareByRun(runId);

                // 2. コンテンツ生成
                var content = BuildContent(project, run, assets, issues, compare);

                // 3. ファイル保存
                Directory.CreateDirectory(ExportFolder);
                var fileName = BuildFileName(project.Title, runId);
                var filePath = Path.Combine(ExportFolder, fileName);

                File.WriteAllText(filePath, content, new UTF8Encoding(true));

                // 4. ログ記録
                _db.CreateExportLog(projectId, runId, filePath);

                return ExportResult.Succeeded(filePath);
            }
            catch (Exception ex)
            {
                return ExportResult.Failed($"エクスポートに失敗しました: {ex.Message}");
            }
        }

        /// <summary>
        /// ファイル名生成
        /// </summary>
        private string BuildFileName(string title, int runId)
        {
            var timestamp = DateTime.Now.ToString("yyyy-MM-dd_HHmmss");
            var safeTitle = SanitizeFileName(title, 20);
            return $"{timestamp}_{safeTitle}_Run{runId:D3}.txt";
        }

        /// <summary>
        /// ファイル名をサニタイズ
        /// </summary>
        private string SanitizeFileName(string input, int maxLength)
        {
            var invalid = Path.GetInvalidFileNameChars();
            var sanitized = new string(input.Where(c => !invalid.Contains(c)).ToArray());
            if (sanitized.Length > maxLength)
                sanitized = sanitized.Substring(0, maxLength);
            return string.IsNullOrWhiteSpace(sanitized) ? "Untitled" : sanitized;
        }

        /// <summary>
        /// エクスポートコンテンツ生成
        /// </summary>
        private string BuildContent(PlProject project, PlRun run, List<PlTextAsset> assets, List<PlIssue> issues, PlCompare? compare)
        {
            var sb = new StringBuilder();
            var sep = new string('=', 80);
            var subsep = new string('-', 80);

            // ヘッダー
            sb.AppendLine(sep);
            sb.AppendLine("PoetryLab Export");
            sb.AppendLine(sep);
            sb.AppendLine($"Project: {project.Title}");
            sb.AppendLine($"Project ID: {project.Id}");
            sb.AppendLine($"Style: {project.StyleType}");
            sb.AppendLine($"Run ID: {run.Id}");
            sb.AppendLine($"Route: {run.RouteName}");
            sb.AppendLine($"Run Started: {run.CreatedAt}");
            sb.AppendLine($"Run Finished: {run.FinishedAt}");
            sb.AppendLine($"Exported: {DateTime.Now:yyyy-MM-ddTHH:mm:ss}");
            sb.AppendLine();

            // 各セクション
            AppendSection(sb, "TOPIC", GetAssetBody(assets, "TOPIC"), "← Input: (なし / ユーザー指定シード)\n← Generated by: POEM_TOPIC_GEN");
            AppendSection(sb, "DRAFT（初稿）", GetAssetBody(assets, "DRAFT"), "← Input: TOPIC\n← Generated by: POEM_DRAFT_GEN");
            AppendSection(sb, "CORE（核）", GetAssetBody(assets, "CORE"), "← Input: DRAFT → CORE_CANDIDATES\n← Adopted by: 人間判断");
            AppendSection(sb, "LINE MAP", GetAssetBody(assets, "LINE_MAP"), "← Input: DRAFT + CORE\n← Generated by: POEM_LINE_MAP");

            // Issues（S/Aのみ）
            sb.AppendLine(sep);
            sb.AppendLine("ISSUES（検出）- S/Aのみ抜粋");
            sb.AppendLine(sep);
            sb.AppendLine("← Input: DRAFT + CORE + LINE_MAP");
            sb.AppendLine("← Generated by: POEM_ISSUE_GEN");
            sb.AppendLine(subsep);
            foreach (var issue in issues)
            {
                sb.AppendLine($"[{issue.Severity}] {issue.Level} - {issue.TargetType}/{issue.TargetIndex}");
                sb.AppendLine($"    症状: {issue.Symptom}");
                if (!string.IsNullOrEmpty(issue.Evidence))
                    sb.AppendLine($"    根拠: {issue.Evidence}");
                sb.AppendLine();
            }

            // Diagnoses
            AppendSection(sb, "DIAGNOSES（診断）", GetAssetBody(assets, "DIAGNOSES"), "← Input: ISSUES\n← Generated by: POEM_DIAGNOSE_GEN");

            // Revisions
            AppendRevisionSection(sb, "REVISION A", GetAssetBody(assets, "REV_A"), "← Input: DRAFT + CORE + DIAGNOSES\n← Generated by: POEM_REVISION_GEN");
            AppendRevisionSection(sb, "REVISION B", GetAssetBody(assets, "REV_B"), "← Input: DRAFT + CORE + DIAGNOSES\n← Generated by: POEM_REVISION_GEN");
            AppendRevisionSection(sb, "REVISION C", GetAssetBody(assets, "REV_C"), "← Input: DRAFT + CORE + DIAGNOSES\n← Generated by: POEM_REVISION_GEN");

            // Winner
            var winnerAsset = assets.FirstOrDefault(a => a.AssetType == "WINNER");
            sb.AppendLine(sep);
            sb.AppendLine("WINNER（採択）");
            sb.AppendLine(sep);
            sb.AppendLine("← Candidates: REV_A / REV_B / REV_C");
            sb.AppendLine($"← Winner: {winnerAsset?.InputKeysUsed ?? "不明"}");
            sb.AppendLine("← Adopted by: 人間判断");
            sb.AppendLine(subsep);
            sb.AppendLine(winnerAsset?.BodyText ?? "(未選択)");
            sb.AppendLine();
            sb.AppendLine(subsep);
            sb.AppendLine("採択理由:");
            sb.AppendLine(compare?.ReasonNote ?? "(理由なし)");
            sb.AppendLine();

            // Notes（プレースホルダー）
            sb.AppendLine(sep);
            sb.AppendLine("NOTES（技法メモ）");
            sb.AppendLine(sep);
            sb.AppendLine("五感:   ");
            sb.AppendLine("比喩:   ");
            sb.AppendLine("音調:   ");
            sb.AppendLine("余韻:   ");
            sb.AppendLine("その他: ");
            sb.AppendLine();

            // Statistics
            sb.AppendLine(sep);
            sb.AppendLine("RUN STATISTICS");
            sb.AppendLine(sep);
            sb.AppendLine("Total Steps: 10");
            sb.AppendLine("AI Steps: 8");
            sb.AppendLine("Human Steps: 2 (Core採択, Winner選択)");
            var allIssues = _db.GetIssuesByRun(run.Id);
            sb.AppendLine($"Issues Found: {allIssues.Count} (S:{allIssues.Count(i => i.Severity == "S")}, A:{allIssues.Count(i => i.Severity == "A")}, B:{allIssues.Count(i => i.Severity == "B")}, C:{allIssues.Count(i => i.Severity == "C")})");
            sb.AppendLine("Revisions Generated: 3");
            sb.AppendLine();

            // Footer
            sb.AppendLine(sep);
            sb.AppendLine("END OF EXPORT");
            sb.AppendLine(sep);
            sb.AppendLine($"Generated by PoetryLab v1");

            return sb.ToString();
        }

        private void AppendSection(StringBuilder sb, string title, string body, string traceInfo)
        {
            var sep = new string('=', 80);
            var subsep = new string('-', 80);
            sb.AppendLine(sep);
            sb.AppendLine(title);
            sb.AppendLine(sep);
            sb.AppendLine(traceInfo);
            sb.AppendLine(subsep);
            sb.AppendLine(body);
            sb.AppendLine();
        }

        private void AppendRevisionSection(StringBuilder sb, string title, string body, string traceInfo)
        {
            AppendSection(sb, title, body, traceInfo);
        }

        private string GetAssetBody(List<PlTextAsset> assets, string assetType)
        {
            return assets.FirstOrDefault(a => a.AssetType == assetType)?.BodyText ?? "(未生成)";
        }
    }
}
